global:
  scrape_interval: 15s
  external_labels:
    monitor: 'localevents'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'localevents'
    scrape_interval: 15s
    static_configs:
      - targets: ['localevents-monorepo.railway.internal:8080']
